import { type AppType } from "next/dist/shared/lib/utils";
import "@task/styles/globals.css";
import Footer from "@task/components/shared/footer";
import Navbar from "@task/components/shared/navbar";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Tag It !</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-between">
        <Navbar />
        <Component {...pageProps} /> <Footer />
      </main>
    </>
  );
};

export default MyApp;
